using System.Diagnostics;
using Xunit;

namespace ThePlayer.TestSupport;

/// <summary>
/// Short H.264 and H.265 clips, generated by FFmpeg when the test run starts.
/// </summary>
/// <remarks>
/// <para>
/// Generated rather than committed. CI then needs no binary assets and no camera, the clips always
/// match the encoder actually installed, and nobody has to explain why a 25 MB mp4 is in the
/// repository.
/// </para>
/// <para>
/// Shared through <c>IClassFixture</c> so the encode happens once per test class rather than once
/// per fact - it is the slowest thing in the integration tier.
/// </para>
/// </remarks>
public sealed class GeneratedMedia : IAsyncLifetime
{
    /// <summary>Ten seconds at 25fps. Small enough to encode quickly, long enough to span keyframes.</summary>
    public const int ExpectedFrames = 250;

    public const int Width = 320;
    public const int Height = 240;
    public const double FrameRate = 25;

    /// <summary>One keyframe per second, so a ten-second clip has ten.</summary>
    public const int ExpectedKeyframes = 10;

    private readonly string _root = Path.Combine(
        Path.GetTempPath(),
        "theplayer-tests",
        Guid.NewGuid().ToString("n")[..12]);

    public string H264File => Path.Combine(_root, "h264.mp4");

    public string H265File => Path.Combine(_root, "h265.mp4");

    /// <summary>The H.264 clip as the streaming pipeline would produce it: Annex-B, with delimiters.</summary>
    public string H264AnnexB => Path.Combine(_root, "h264.annexb");

    public string H265AnnexB => Path.Combine(_root, "h265.annexb");

    /// <summary>
    /// The same clip as the server-decoding pipeline would produce it: a stream of whole JPEGs.
    /// </summary>
    /// <remarks>
    /// Encoded at the default quality rather than a low one, deliberately. A high-quality JPEG is
    /// large enough to span several reads of the pipeline's buffer, which is where a reader that
    /// mishandles a marker straddling a read boundary gives itself away.
    /// </remarks>
    public string Mjpeg => Path.Combine(_root, "pictures.mjpeg");

    public async Task InitializeAsync()
    {
        Directory.CreateDirectory(_root);

        var source = $"testsrc2=size={Width}x{Height}:rate=25:duration=10";

        await RunAsync(
            $"-y -hide_banner -loglevel error -f lavfi -i \"{source}\" " +
            $"-c:v libx264 -preset ultrafast -pix_fmt yuv420p -g 25 \"{H264File}\"");

        await RunAsync(
            $"-y -hide_banner -loglevel error -f lavfi -i \"{source}\" " +
            $"-c:v libx265 -preset ultrafast -pix_fmt yuv420p " +
            $"-x265-params \"keyint=25:log-level=none\" -tag:v hvc1 \"{H265File}\"");

        // The exact bitstream filters FFmpegStreamingPipeline uses. dump_extra is what puts the
        // parameter sets in front of every keyframe; without it the elementary stream carries IDR
        // frames and no SPS, and nothing downstream can configure a decoder.
        await RunAsync(
            $"-y -hide_banner -loglevel error -i \"{H264File}\" -an -c:v copy " +
            $"-bsf:v h264_metadata=aud=insert,dump_extra=freq=keyframe -f h264 \"{H264AnnexB}\"");

        await RunAsync(
            $"-y -hide_banner -loglevel error -i \"{H265File}\" -an -c:v copy " +
            $"-bsf:v hevc_metadata=aud=insert,dump_extra=freq=keyframe -f hevc \"{H265AnnexB}\"");

        // No bitstream filter and no delimiters: JPEG images carry their own boundaries.
        await RunAsync(
            $"-y -hide_banner -loglevel error -i \"{H264File}\" -an -c:v mjpeg -q:v 5 " +
            $"-f mjpeg \"{Mjpeg}\"");
    }

    public Task DisposeAsync()
    {
        try
        {
            Directory.Delete(_root, recursive: true);
        }
        catch (Exception)
        {
            // A temp directory that outlives the run is untidy, not a test failure.
        }

        return Task.CompletedTask;
    }

    private static async Task RunAsync(string arguments)
    {
        using var process = new Process
        {
            StartInfo = new ProcessStartInfo
            {
                FileName = "ffmpeg",
                Arguments = arguments,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true,
            },
        };

        try
        {
            process.Start();
        }
        catch (Exception ex)
        {
            throw new InvalidOperationException(
                "These are integration tests and need FFmpeg on PATH.",
                ex);
        }

        // Both streams drained before waiting, for the same reason the production runner does it:
        // a full pipe buffer blocks the child, and FFmpeg is never quiet on stderr.
        var output = process.StandardOutput.ReadToEndAsync();
        var error = process.StandardError.ReadToEndAsync();

        await process.WaitForExitAsync();
        await Task.WhenAll(output, error);

        if (process.ExitCode != 0)
        {
            throw new InvalidOperationException(
                $"ffmpeg {arguments} failed with {process.ExitCode}: {await error}");
        }
    }
}
